global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 25.0
  publish_frequency: 10.0
  static_map: true
  resolution: 0.050000 # 새로 추가
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.5 # 경로를 만들 때 장애물에서 얼마나 떨어질 지 결정
  cost_scaling_factor: 10.0 # 장애물 근처에서 경로 우선순위가 급격히 증가
