global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  #static_map: true
  transform_tolerance: 1.0  # transform_tolerance 추가
  
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/map"
  
  obstacle_layer:
    obstacle_range: 2.0
    raytrace_range: 2.5
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

  inflation_layer:
    inflation_radius: 0.25

